title = "Das ist ein Test"
baseURL = "https://interrail22.nafn.de/"
languageCode = "de-de"
theme = "ananke"

DefaultContentLanguage = "de"
Paginate = 20
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Urlaub mit dem Zug"
    weight = 1
    contentDir = "content/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  show_reading_time = true

  text_color = "#000000"
  author = "Malte"
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10
